services:

  postgres:
    image: postgres:17

    container_name: recruitment-db

    environment:
      POSTGRES_DB: recruitment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: recruitment-app

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data: